### ISSUE TITLE
สร้าง Order ไม่ได้

### ISSUE THREAD

**Issue by hanam1ni** [mrnonz/mejai#95]
Request: https://jsoneditoronline.org/?id=7b81c46a4e702745dc43ed42ece7cf4e

**Comment by hanam1ni** [comment]
![Postman.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599ed0429bbc87001f58fc88/125516c66e82c728ace21e0d46d89b89378f82a7cda5fd53b652fa912a5265296b51fa727586e071ed122f04585a4aac4109584dfbfd887da0a42062c80d55b98e30063e937f03a6aa8318b500bf22884784b6b5884fc3e93537aa.png)

**Comment by hanam1ni** [comment]
ถ้าสร้างได้แล้วลอง ทดสอบ GET ด้วยนะ

**Comment by mrnonz** [comment]
return only HTTP_status = 200
